lib: Refactor command handing and responses.
Commands have been refactored so that Instance#command can now check
their arity and catch incorrect parameters early. This obviates
the need for Instance#method_missing and makes the flow
slightly more readable.

Commands now return "responses," which are hashes that contain,
at minimum, three guaranteed keys:

	error: an error message, or nil if no error has occurred.
	data: any relevant data from the command.
	method: the method corresponding to the command.

This allows for two-way interaction beyond that previously available
through informational output.

Bump muzak to 0.1.0. It's still not stable, but we're getting there.